title: "Color Space Fixer"
remote_theme: pmarsceill/just-the-docs
aux_links:
  "GitHub":
    - "https://github.com/CreunaFI/color-space-fixer"
defaults:
  -
    scope:
      path: ""
    values:
      image: "color-space-fixer.png"
