name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Release
      run: |
        zip -r color-space-fixer.zip . -x *.git*

    - uses: actions/upload-artifact@master
      with:
        name: color-space-fixer.zip
        path: color-space-fixer.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: color-space-fixer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
